### ISSUE TITLE
Перенос фигурных скобок на цифры.

### ISSUE THREAD

**Issue by korenevskiy** [A-Projects/Ruchey#13]
Предлагаю перенести квадратные скобки.
-Символы "[", "]" предлагаю перенести на кнопки [-_], [=+].
расположив символы "[", "]" в новом месте, они будут гармонично располагаться ровно над "{", "}", одновременно они будут логически располагаться рядом с символами "(", ")".

-Так же рекомендую поменять символы ₽ и ~ местами. Всё-таки знак рубля уже используется на кнопке 8. При этом тильда будет находится близко к изначальному расположению рядом с кнопкой Ё

**Comment by a-projects** [comment]
Ваше предложение логично, но есть «но».

Много запросов на математические символы, поэтому «-» и «=» оставлено под «±» и «≠».
Набор квадратных скобок одной рукой на «ж» и «э» очень прост, попробуйте сами.
Тильда на «8», чтобы удобно было набирать домашний каталог «~/».
Да и «₽» только Windows раскладке на «8», в остальных ОС это не так.

**Comment by korenevskiy** [comment]
> Много запросов на математические символы, поэтому «-» и «=» оставлено под «±» и «≠». Набор квадратных скобок одной рукой на «ж» и «э» очень прост, попробуйте сами. Тильда на «8», чтобы удобно было набирать домашний каталог 

Ну тогда квадратные скобки можно оставить на Х и Ъ. А фигурные переместить на - и =.



> «~/». Да и «₽» только Windows раскладке на «8», в остальных ОС это не так.

А в остальных по дефолту где расположено?
