### ISSUE TITLE
Раскладка не работает в телеграмм-е (макос)

### ISSUE THREAD

**Issue by towingie** [A-Projects/Ruchey#14]
после установки всё отлично работает, везде, кроме Telegramm-а. пока в Телеграмм-е отказывается переключаться на русскую инженерную. на системную русскую отлично переключается.

(видимо каких-то установленных чудо-флажков не хватает)

**Comment by a-projects** [comment]
С маками не просто, даже типы клавиатур отличаются. 
Я могу протестировать только в Catalina на MacPro  и Big Sur в VirtualBox.
На данный момент и в Catalina и Big Sur в Telegram и ICQ обе раскладки работают.

Давайте попробуем локализовать проблему.
1) При установке использовали bundle или dmg?
2) Устанавливали как локальную (каталог ~/Library) или как системную (каталог /Library)?

Я рекомендую устанавливать как системную и после добавления в настройках перезагрузить ОС.

**Comment by towingie** [comment]
0. Я на Ventura-e (12.5.1)
0.1 язык (интерфейса) английский
0.2 region Russia/Moscow
0.3 С matrix messenger (на базе хромовского электрона) проблем никаких, всё работает, как и в хроме и тп, как и во всех приложеньках какие использую (ну за исключением Telegramm)

1. бандл, клонированный из репы на гитхабе
2. Закидывал бандл в ~/Library/Keyboard Layouts, так как в написано в доке по инсталяции (для конкретного пользователя)

Пробовал по всякому (свою раскладочку редактировать) и language,  locale, и region, и без них, работает везде, кроме телеграмм-а

галочка переключатся на язык документа - никакого влияния не оказывают

**Comment by towingie** [comment]
и тут я решил обновиться до 12.6... всё и починилось. :-/

при жопсе такого не было (с)

**Comment by a-projects** [comment]
Ventura это же пока только в Preview. Хорошо, что починили баг, было бы печально на новом Mac получить такие проблемы.
