### ISSUE TITLE
En variant does not include ; , . symbols

### ISSUE THREAD

**Issue by ilyxa** [A-Projects/Ruchey#16]
xkeyboard-config 2.36+91+g28b21415-1

`setxkbmap -option grp:lalt_toggle,shift:both_capslock_cancel,lv3:ralt_switch -layout "ru,ru" -variant ruchey_en,ruchey_ru -model pc104`

No directly accesible symbols , . ; (only somewhere in 2nd layer) in en variant. Is it expected behaivor?

Do I miss something?

**Comment by a-projects** [comment]
Да, это ожидаемое поведение. Обе раскладки базируются на русской. Точка и запятая расположена справа от «Ю», точка с запятой на цифре «4». Они намеренно сделаны одинаковыми и отличаются только буквами. Английских букв меньше и по этой причине Вы заметите «пустые» клавиши. 

- Английский вариант идёт как дополнение и полезен больше для простых пользователей, которые не понимают почему в точка в базовой русской и базовой английской раскладке имеют разное положение. 
- Английский вариант 100% не удобен тем, кто работает на большом числе ПК, например администраторам,
- Для программистов, которые пользуются одним ПК, английская раскладка слегка снижает скорость набора кода, но в целом упрощает набор комментариев и переписки в чатах.

По сути многие выбирают русскую «ручей» и английскую базовую. Ничего не теряют, но в русской могут вводить все спецсимволы без переключение раскладки.
