### ISSUE TITLE
Горячие клавиши KDE на Fedora Linux 37

### ISSUE THREAD

**Issue by cryptozoy** [A-Projects/Ruchey#18]
Когда в настройках поднимаешь наверх русскую раскладку, то перестают работать горячие клавиши по умолчанию, видимо связанные с английскими буквами. Переназначение горячих клавиш на русские буквы не даёт результата. Горячие клавиши всё равно не работают. Если это невозможно исправить, то напишите об этом в документации по настройке раскладок в KDE. Пользователи не в курсе проблемы и могут случайно ошибиться при настройке. То есть наверху всегда должна быть английская раскладка, тогда всё работает.

**Comment by a-projects** [comment]
Эта проблема повсеместна, многие тулкиты связывают комбинации не с физическими номерами клавиш, а именно с символами. Самый простой пример - VLC в Windows не реагирует на быстрые клавиши, если включена раскладка с русскими символами. В VSCode тоже есть проблемы, правда несколько иные. Кстати глобальные комбинации в KDE, например Meta+D, работают даже если вверху раскладка с русскими символами.

В Fedora 38 инженерные раскладки доступны уже из коробки, правда переведены как "Русская (инженерная, кириллица)" и "Русская (инженерная, латиница)".

А в документацию, да, наверное стоит добавить.

**Comment by a-projects** [comment]
Судя по всему в это починено. Я попробовал в Kubuntu 22.10, Kde neon unstable (KDE6). В штатных приложениях, VSCode, Firefox, в самом DE быстрые клавиши работают не зависимо какая раскладка вверху.
