### ISSUE TITLE
Клавиша-модификатор для временного переключения языка в Windows

### ISSUE THREAD

**Issue by cryptozoy** [A-Projects/Ruchey#19]
Интересует возможность печатать английские буквы находясь в русском языке во время нажатия и удержания какой-нибудь дополнительной клавиши-модификатора, но не переключаясь на постоянно в английский язык, и наоборот. Или такая функция уже реализована под Windows?

**Comment by a-projects** [comment]
Для Windows переключения по удержанию я не встречал. Иногда это закладывают прямо в раскладках, но в данном случае это не подходящее решение. Извиняюсь за мою оочень медленную реакцию на issue ;)
