### ISSUE TITLE
Ударные гласные буквы через AltGr

### ISSUE THREAD

**Issue by ValdikSS** [A-Projects/Ruchey#2]
Хоть это может и не подходить под понятие _инженерной_ раскладки, предлагаю добавить гласным буквам ударные версии через AltGr:
а → а́
о → о́
е → е́
и т.д.

Либо же добавить U+000301 COMBINING ACUTE ACCENT отдельной комбинацией.

**Comment by a-projects** [comment]
Можно. По сути из акцентов нужен только акут.
Обычно это делается действиями: в Windows Alt+«0769», в Linux Ctrl+Shift+«U0301», но это определённо неудобно.

Символ а́ составной «U+0430U+0301» (а и акут). 
Получается, что нужна только комбинация для символа «U+0301».
Т.к. символ невидимый, то считаю, что его нужно вынести на 4-й уровень: AltGr+Shift+`.
Это явно ускорит набор людям, которым это нужно, но при этом не будет мешаться с остальными символами.

Составные символы лучше не использовать т.к. реализация также затрагивает Windows.
Акценты гравис, умлаут и д.р. считаю, что вводить не стоит, по крайней мере, пока не будет явного запроса.
