### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by cryptozoy** [A-Projects/Ruchey#20]
Дублируется последний вопрос/ответ:

Вопрос: Эта раскладка специально для 1С программистов?
Ответ: Я не являюсь 1С программистом, но думаю, что она прекрасно подойдёт.

Вопрос: Эта раскладка специально для 1С программистов?
Ответ: Я не являюсь 1С программистом, но думаю, что она прекрасно подойдёт.

**Comment by a-projects** [comment]
Спс :)
