### ISSUE TITLE
Добавить математические и экономические символы

### ISSUE THREAD

**Issue by Andrey-Boston** [A-Projects/Ruchey#3]
Предлагаю добавить математические символы:
≠, ±, ≤, ≥, ≈, ∞, ÷, ×

Экономические:
™, ®, ©, €

**Comment by a-projects** [comment]
Юридические знаки можно добавить в четвёртый уровень, как потенциально нужные, «R», «C», «T». Экономические на третий уровень: евро (€) -> «E», юань (¥) -> «Y».

**Comment by a-projects** [comment]
А вот с математическими нужно разбираться.
1) Есть символы, которые не универсальны и не используются в наборе, такие как «±» и их вообще не стоит добавлять в раскладку. За их набор должно отвечать отдельное приложение с выбором символа.
2) Есть символы не актуальные на текущий монет, такие как «∞». Их стоит вводить по потребности, например кто-то собрался их использовать в языке программирования и часто набирать.
2) Есть замещённые символы: «*» замещает «×», «/» замещает «÷» , аналогично конъюнкция «&» и дизъюнкция «|». Их также не стоит водить. За визуальное преобразование может отвечать среда (среда разработки, офисный пакет).
3) Есть составные символы «!=» -> «≠», «<=» -> «≤» За них также должна отвечать среда или шрифт. В некоторых IDE используются шрифты с лигатурами, которые, визуально заменяют комбинацию символов на один (JetBrains Mono). К тому же введение символа «≠» создаёт сложности в ЯП т.к. очень часто для сравнения используется «==». Кстати символ «≡» попадает в туже ловушку. 

Как итог:
Математические символы должны формировать среда или шрифты с лигатурами.
