### ISSUE TITLE
Возможность использования ahk для переключения между раскладками

### ISSUE THREAD

**Issue by oswid** [A-Projects/Ruchey#5]
Добрый день, 

Давно пользуюсь ahk в Виндоус для одностороннего переключения на определенные языки. Обычно не составляет труда найти id раскладки языка и потом уже его использовать в скрипте по нажатию определенной клавиши.

Проблема id данных раскладок заключаются в том, что они несколько отличаются от о обычных : вот id английского языка, стандартной раскладки кверти: 0x4090409 , в то время как инженерные : 0xF0C10419 для кириллицы и 0xF1C10419 для латиницы.

Подобное решение не работает

```ahk
OnLocale(InputLocaleID)  {
    ControlGetFocus, CtrlFocus, % "ahk_id" WinExist("A")
    PostMessage, 0x50, 0, InputLocaleID, %CtrlFocus%
}


~RShift::OnLocale(0xF0C10419) ; to Russian
~RCtrl::OnLocale(0xF0C00419)  ; to English
```

Было бы интересно узнать, возможно функционал перехода на определенную раскладку языка реализовать в системе виндоус с помощью других способов, либо же изменить id раскладки на поддерживаемый в ahk. Циклический переход по раскладкам не решает необходимых задач

**Comment by oswid** [comment]
Проблему решил, можно будет добавить в описание:

```ahk
OnLocale(InputLocaleID)  {
    ControlGetFocus, CtrlFocus, % "ahk_id" WinExist("A")
    PostMessage, 0x50, 0, InputLocaleID, %CtrlFocus%
}


~RShift::OnLocale(-0xF3EFBE7) ; to Russian
~RCtrl::OnLocale(-0xF3FFBE7)  ; to English
```

**Comment by a-projects** [comment]
Интересная идея повесить переключение не на Caps, а на правый Ctrl / Shift !
Я пользуюсь простым вариантом: 
<pre>
SetCapsLockState, AlwaysOff
+CapsLock::CapsLock

CapsLock::Send, {Ctrl down}{Shift down}{Shift up}{Ctrl up}{Ctrl up}
return
</pre>

Как будет время добавлю в оба варианта в HOWTO

**Comment by oswid** [comment]
На деле, это имеет намного больший смысл, когда клавиатура программируемая и имеет иной вид
![DSC01001-3](https://user-images.githubusercontent.com/76834058/188310595-e053f688-5da5-423b-af7c-fcecb7b65dac.jpg)

**Comment by a-projects** [comment]
Да, так-то можно назначить в любое удобное место переключение раскладок. 

На самом деле самым офигенным был бы вариант с еще одним рядом клавиш под цифры. Т.е. спецсимволы отдельно, цифры отдельно. Я делал похожий макет, выносил цифры на 3-й слой, это был интересный опыт. К сожалению в таком макете набирать IP адреса - это боль.
