### ISSUE TITLE
Don't work in ubuntu 22.04

### ISSUE THREAD

**Issue by free-archer** [A-Projects/Ruchey#8]
I installed a deb package used dpkg -i
Then i added keylayout in the Ubuntu settings. The key hit from task bar.
I edited /etc/default/keyboard how to say in help and I run dpkg-reconfigure -phigh console-setup  - it did not give any results. 

Now i have only en-keylayout.

What do i wrong?

**Comment by a-projects** [comment]
After installing the package, you must reboot the system.
X11 sometimes accepts new layouts. But the console only after reboot.
After reboot need execute command `dpkg-reconfigure -phigh console-setup`.
Again reboot and check it.

Let me know if it didn't work.

**Comment by free-archer** [comment]
Да теперь все получилось, спасибо! Неплохо бы это в описание добавить. 
И вот скрин, какие ещё нужно сделать настройки в ubuntu.
![image](https://user-images.githubusercontent.com/36464371/188480323-3675d696-9021-4f3b-ba03-354206f7cc0a.png)

**Comment by a-projects** [comment]
Принято. Добавлю в описание для новой версии
