### ISSUE TITLE
Рассмотреть возможность разбить раскладки на Русский и Английский вариант

### ISSUE THREAD

**Issue by a-projects** [A-Projects/Ruchey#9]
Вызывает вопросы:
1) Неудобство, когда в индикаторе раскладок Gnome: ru1, ru2; KDE ru, ru; Windows РУС, РУС.
2) Для Mac изначально нет возможности переключения между ru, ru по CapsLock. Текущая реализация en, ru.
3) При использовании обозначения «кириллица» и «латиница» происходит не совсем корректная классификация.

**Comment by a-projects** [comment]
Причины почему именно ruchey_cyrillc и ruchey_latin:
Есть проблема создания раскладки для Windows на основе английской. Всё печально с юникодом - в базе win-1252.
Также вопрос к Mac и KDE - какой флаг использовать для Английского варианта. США?
В целом по Linux - пропустят ли в мэйнстриме Английский вариант в перечень en раскладок?

**Comment by oswid** [comment]
Как вариант найти сторонний способ индикации языка, через тот же ahk, для переключения языка на линуксе и маке  пишется скрипт и вешается на клавишу.

**Comment by a-projects** [comment]
Решены проблемы идентификации в Gnome, KDE. Для Mac положение дел остаётся таким же переключение языка, а не раскладки. Изменено название ruchey_cyrillc -> ruchey_ru, ruchey_latin -> ruchey_en.
